group.id=connect-group
status.storage.replication.factor=1
key.converter=org.apache.kafka.connect.json.JsonConverter
config.storage.topic=connect-configs
offset.storage.replication.factor=1
plugin.path=/usr/share/java,/etc/kafka-connect/jars
offset.storage.topic=connect-offsets
bootstrap.servers=kafka:9092
value.converter=org.apache.kafka.connect.json.JsonConverter
rest.advertised.host.name=kafka-connect
rest.port=8083
status.storage.topic=connect-status
config.storage.replication.factor=1
